version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    depends_on:
      - server
    restart: always
    environment:
      - VITE_API_BASE_URL=http://fullst-Publi-d0tjcsK9Ryx0-1935965929.us-west-1.elb.amazonaws.com

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env.prod
    restart: always
