version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    depends_on:
      - server
    restart: always

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env.prod
    restart: always
