version: '3.8'

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:80"
    env_file:
      - ./client/.env
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    env_file:
      - ./server/.env